// Action types without side effects :)

// Threads
export const LOAD_THREADS_DATA = 'LOAD_THREADS_DATA'
export const ERROR_LOAD_THREADS_DATA = 'ERROR_LOAD_THREADS_DATA'
export const LOAD_MORE_THREADS_DATA = 'LOAD_MORE_THREADS_DATA'
export const FILTER_THREADS = 'FILTER_THREADS'
export const UPVOTE_THREAD = 'UPVOTE_THREAD'
export const DOWNVOTE_THREAD = 'DOWNVOTE_THREAD'

// Comments
export const LOAD_COMMENTS_DATA = 'LOAD_COMMENTS_DATA'
export const ERROR_LOAD_COMMENTS_DATA = 'ERROR_LOAD_COMMENTS_DATA'
export const LOAD_MORE_COMMENTS_DATA = 'LOAD_MORE_COMMENTS_DATA'
